marked-plaintify port to Marked v13
bent10/marked-extensions pull request #101
Opened 2024-07-14 04:30 UTC by irian-codes

Hello! 👋

I'm using your library in a personal project,and I noticed it was crashing on Marked latest v13 version. So I decided to update it so it works well. It's helping me parse Markdown into plain text so I can embed it into a vector database for LLMs to retrieve it, so thank you for your work!

Seems Marked pushed breaking changes with the [v13 release](https://github.com/markedjs/marked/releases/tag/v13.0.0) and I tried to adapt it. Tests pass, for all packages (the only one failing was plaintify) so it seems good.

I had to introduce [a breaking change](https://github.com/bent10/marked-extensions/commit/b3f11f905c1f83d5bf5f9f62f6a34b6dd7b6c982), which is passing the Marked instance to the function. This seems necessary because the new way they're doing it calls the Parser instance ([old way](https://github.com/markedjs/marked/blob/c6a98ea66c36d12255543e2fabd8f8236dbc5276/src/Renderer.ts#L69)) vs ([new way](https://github.com/markedjs/marked/blob/master/src/Renderer.ts#L108)). However, if you know any way this breaking change could be avoided let me know!

This is my first open source contribution so sorry if I made anything wrong 🙏

Have a great day!

2024-07-17 14:41 UTC, irian-codes commented
Thank you for your words!

I'm glad my solution seems solid to you. I've made a new commit adding the error comments so you can read and review them whenever you can. It’s been great contributing to this project, and I’m excited to see it integrated.

Thanks for the library, it's very useful 😊

2024-07-18 11:22 UTC, bent10 requested changes
I think we can avoid the breaking change by using `this.render` within the renderer function. This approach should also resolve the TypeScript errors. Please check the following code:

```ts
import { Renderer, MarkedExtension, RendererObject } from 'marked'

/**
 * Options for configuring the markedPlaintify extension.
 */
export type Options = RendererObject & {
  /**
   * Custom 3rd-party renderers.
   */
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  [k: string]: (this: Renderer, ...args: any[]) => string | false
}

/**
 * A [marked](https://marked.js.org/) extension to convert Markdown to Plaintext.
 */
export default function markedPlaintify(
  options: Options = {}
): MarkedExtension {
  const plainTextRenderer: Options = {}
  const mdIgnores: string[] = ['constructor', 'hr', 'checkbox ', 'br', 'space']
  const mdInlines: string[] = ['strong', 'em', 'del']
  const mdEscapes: string[] = ['html', 'code']

  let currentTableHeader: string[] = []

  Object.getOwnPropertyNames(Renderer.prototype).forEach(prop => {
    if (mdIgnores.includes(prop)) {
      // ignore certain Markdown elements
      plainTextRenderer[prop] = () => ''
    } else if (mdInlines.includes(prop)) {
      // preserve inline elements
      plainTextRenderer[prop] = function (token) {
        const text = this.parser.parseInline(token.tokens)
        return text
      }
    } else if (mdEscapes.includes(prop)) {
      // escaped elements
      plainTextRenderer[prop] = token => escapeHTML(token.text) + '\n\n'
    } else if (prop === 'codespan') {
      // handle codespan
      plainTextRenderer[prop] = token => escapeHTML(token.text)
    } else if (prop === 'list') {
      // handle list element
      plainTextRenderer[prop] = function (token) {
        let text = ''
        for (let j = 0; j < token.items.length; j++) {
          const item = token.items[j]
          const renderedItem = plainTextRenderer.listitem?.call(this, item)

          if (typeof renderedItem === 'string') {
            text += renderedItem.replace(/\n{2,}/g, '\n')
          }
        }

        return '\n' + text.trim() + '\n\n'
      }
    } else if (prop === 'listitem') {
      // handle list items
      plainTextRenderer[prop] = function (token) {
        const text = this.parser.parse(token.tokens)
        return '\n' + text.trim()
      }
    } else if (prop === 'blockquote') {
      // handle blockquote
      plainTextRenderer[prop] = function (token) {
        const text = this.parser.parse(token.tokens)
        return text.trim() + '\n\n'
      }
    } else if (prop === 'table') {
      // handle table elements
      plainTextRenderer[prop] = function (token) {
        currentTableHeader = []

        // parsing headers
        for (let j = 0; j < token.header.length; j++) {
          plainTextRenderer.tablecell?.call(this, token.header[j])
        }

        // parsing rows
        let body = ''
        for (let j = 0; j < token.rows.length; j++) {
          const row = token.rows[j]
          let cell = ''
          for (let k = 0; k < row.length; k++) {
            cell += plainTextRenderer.tablecell?.call(this, row[k])
          }
          body += plainTextRenderer.tablerow?.call(this, { text: cell })
        }

        return body
      }
    } else if (prop === 'tablerow') {
      // handle table rows
      plainTextRenderer[prop] = token => {
        const chunks = token.text.split('__CELL_PAD__').filter(Boolean)

        return (
          currentTableHeader
            .map((title, i) => title + ': ' + chunks[i])
            .join('\n') + '\n\n'
        )
      }
    } else if (prop === 'tablecell') {
      // handle table cells
      plainTextRenderer[prop] = function (token) {
        const text = this.parser.parseInline(token.tokens)

        if (token.header) {
          currentTableHeader.push(text)
        }

        return text + '__CELL_PAD__'
      }
    } else if (prop === 'link') {
      // handle links
      plainTextRenderer[prop] = function (token) {
        const text = this.parser.parseInline(token.tokens)
        return text + '\n\n'
      }
    } else if (prop === 'image') {
      // handle images (links starting with !)
      plainTextRenderer[prop] = token => {
        return token.text + '\n\n'
      }
    } else if (prop === 'paragraph') {
      // handle paragraphs (which sometimes link and images lines are detected as well)
      plainTextRenderer[prop] = function (token) {
        let text = this.parser.parseInline(token.tokens)

        // Removing extra newlines introduced by other renderer functions
        text = text.replace(/\n{2,}/g, '')

        return text + '\n\n'
      }
    } else if (prop === 'heading') {
      // handle headings
      plainTextRenderer[prop] = function (token) {
        const text = this.parser.parseInline(token.tokens)
        return text + '\n\n'
      }
    } else {
      // handle other elements
      plainTextRenderer[prop] = function (token) {
        return 'tokens' in token && token.tokens
          ? this.parser.parseInline(token.tokens)
          : token.text
      }
    }
  })

  return {
    useNewRenderer: true,
    renderer: {
      ...plainTextRenderer,
      ...options
    }
  }
}

// rest of code...
```

Additionally, please update the `package.json` file to specify the peer dependency for `marked`:

```json
{
  ...,
  "peerDependencies": {
    "marked": ">=13.0.0"
  }
}
```

2024-07-29 17:53 UTC, irian-codes commented
Of course! Using the `function` syntax uses the `this` value from the caller, great approach! I've run the tests too and it works.

Furthermore, since we're already setting `this` correctly now, I think we can revert all the `plainTextRenderer.[function]?.call(this, args)` to the previous ones so `plainTextRenderer.tablecell?.call(this, token.header[j])` becomes `this.tablecell(token.header[j])`, right?

Check out [this code](https://github.com/irian-codes/marked-extensions/blob/plaintify-port-v13-this-fix/packages/plaintify/src/index.ts). It passes all tests and has zero Typescript errors 😁

2024-07-30 07:45 UTC, bent10 commented
That’s fantastic! You can push your code for merging.

However, if you don’t mind, I recommend creating a new pull request to avoid the `BREAKING CHANGE:` token on commit b3f11f9. Otherwise, it will trigger `semantic-release` to create a major version release when CI runs.

> BTW sorry for the delay, I had to attend family these days and I wasn't available.

No worries, this is an open source project 😃

2024-07-30 16:30 UTC, irian-codes commented
Closing in favour of [PR 104](https://github.com/bent10/marked-extensions/pull/104) which doesn't include breaking changes so CI doesn't get triggered.

2024-07-30 16:30 UTC, closed without merging